### ISSUE TITLE
Про бд

### ISSUE THREAD

**Issue by dratdin** [jeniaefimov/ShotShare#1]
О руби, красавчик :) Загружать drag and dropом надеюсь можно будет. И почему mySQL ? В Рельсах же есть встроенная БД, поделись пожалуйста, мб и я mySQL у себя буду использовать.

**Comment by jeniaefimov** [comment]
Да загружать drag&drop можно будет обязательно. Насчет mySQL я погорячился, наверное стоит пока использовать дефолтную рубевую sqlite3. Спасибо за совет.
